# @package _global_

defaults:
  - md

data:
  datamodule:
    dataset:
      mol_name: benzene

ckpt_path:
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_43/10061487_benzene_slurm__seed-2"
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_44/10061488_benzene_slurm__seed-3"
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_45/10061489_benzene_slurm__seed-4"
