# @package _global_

defaults:
  - md

data:
  basis_info:
    atomic_numbers: [1, 6, 8]
  datamodule:
    dataset:
      mol_name: phenol

ckpt_path: 
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_30/10061472_phenol_slurm__seed-2"
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_32/10061476_phenol_slurm__seed-3"
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_33/10061477_phenol_slurm__seed-4"