# @package _global_

defaults:
  - override /data: qm9_vasp_small
  - override /data/datamodule/dataset/transform: test_default

data:
  basis_info:
    basis: "gth-tzv2p"

ckpt_path: 
  - "/export/scratch/mklockow/boa/models/train/runs/543_qm9_small_qm9_vasp_small_gth_basis__seed-2"
  - "/export/scratch/mklockow/boa/models/train/runs/544_qm9_small_qm9_vasp_small_gth_basis__seed-3"
  - "/export/scratch/mklockow/boa/models/train/runs/545_qm9_small_qm9_vasp_small_gth_basis__seed-4"