# @package _global_

defaults:
  - override /data: qm9_vasp_small
  - override /data/datamodule/dataset/transform: test_default
  

ckpt_path: 
  - "/export/scratch/mklockow/boa/models/train/runs/503_qm9_small__localscratch_mklockow_charge_density_lmdb_charge_density_lmdb___qm9_vasp_small_large_cutoff__seed-2"
  - "/export/scratch/mklockow/boa/models/train/runs/504_qm9_small__localscratch_mklockow_charge_density_lmdb_charge_density_lmdb___qm9_vasp_small_large_cutoff__seed-4"
  - "/export/scratch/mklockow/boa/models/train/runs/505_qm9_small__localscratch_mklockow_charge_density_lmdb_charge_density_lmdb___qm9_vasp_small_large_cutoff__seed-3"