# @package _global_

defaults:
  - override /data: qm9_vasp_small
  - override /data/datamodule/dataset/transform: test_default

data:
  basis_info:
    basis: "def2-TZVP"

ckpt_path: 
  - "/export/scratch/mklockow/boa/models/train/runs/537_qm9_small_qm9_vasp_small_medium_basis__seed-2"
  - "/export/scratch/mklockow/boa/models/train/runs/538_qm9_small_qm9_vasp_small_medium_basis__seed-3"
  # - "/export/scratch/mklockow/boa/models/train/runs/540_qm9_small_qm9_vasp_small_medium_basis__seed-4"