# @package _global_

defaults:
  - override /data: qm9_psycf
  - override /data/datamodule/dataset/transform: test_default

ckpt_path: "/export/scratch/mklockow/boa/models/train/runs/450_qm9_small_benzene__seed-4/epoch=1269-step=96520.ckpt"