# @package _global_

defaults:
  - md

data:
  basis_info:
    atomic_numbers: [1, 6, 8]
  datamodule:
    dataset:
      mol_name: resorcinol

ckpt_path:
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_27/10061468_resorcinol_slurm__seed-2"
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_28/10061469_resorcinol_slurm__seed-3"
  - "/export/data/ialgroup/mklockow/boa/helix_models/train/slurm_multiruns/run_29/10061471_resorcinol_slurm__seed-4"