# defaults:
#   - model_checkpoint
#   - early_stopping
#   - model_summary
#   - rich_progress_bar
#   - _self_

# model_checkpoint:
#   dirpath: ${paths.output_dir}/checkpoints
#   filename: "epoch_{epoch:03d}"
#   monitor: "val/acc"
#   mode: "max"
#   save_last: True
#   auto_insert_metric_name: False

# early_stopping:
#   monitor: "val/acc"
#   patience: 100
#   mode: "max"

# model_summary:
#   max_depth: -1

- _target_: lightning.pytorch.callbacks.EarlyStopping
  patience: 10000
  verbose: False
  monitor: ${monitor.metric}
  mode: ${monitor.mode}

- _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}
  save_top_k: 5
  save_last: True
  verbose: False
  monitor: ${monitor.metric}
  mode: ${monitor.mode}

- _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "step"
  log_momentum: False

- _target_: lightning.pytorch.callbacks.progress.tqdm_progress.TQDMProgressBar
  refresh_rate: 1