defaults:
  - data: qm9_vasp_small
  - model: qm9
  - paths: default
  - hydra: default
  - trainer: default
  - optim: adam
  - lr_scheduler: cosine_annealing
  - callbacks: default
  - logger: tensorboard
  - _self_

name: qm9_small

task_name: train

initial_guess_pre_training_steps: 1000
pre_training_overrides:
  optim:
    lr: 0.01
  trainer:
    max_steps: ${initial_guess_pre_training_steps}
  model:
    use_radial_correction: false
  data:
    datamodule:
      n_probe:
        train: 48000

pre_training_replacements:
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 250
    T_mult: 1

conventions:
  x_key: 'x'
  y_key: 'y'

# reproducibility
seed: 0
deterministic: False

lr_schedule_freq: 1

ema:
  decay: 0.995

restore:
  ckpt_or_run_path: null
  mode: null # null, finetune, hotstart, continue

monitor:
  metric: 'loss/val'
  mode: 'min'

log_train_nmape_interval: 10

ckpt_path: null
weight_ckpt_path: null