defaults:
  - data: qm9
  - model: qm9
  - paths: default
  - hydra: default
  - trainer: default
  - optim: adam
  - lr_scheduler: cosine_annealing
  - callbacks: default
  - logger: tensorboard
  - _self_

# metadata specialised for each experiment
# core:
#   expname: debug
#   project_name: scdp
#   storage_dir: ${core.expname}
#   version: 0.0.1
#   tags: null
name: debug

task_name: train

conventions:
  x_key: 'x'
  y_key: 'y'

# reproducibility
seed: 0
deterministic: False

lr_schedule_freq: 1

ema:
  decay: 0.995

restore:
  ckpt_or_run_path: null
  mode: null # null, finetune, hotstart, continue

monitor:
  metric: 'loss/val'
  mode: 'min'