# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

# BaseConf

timeout_min: 4320
nodes: 1
tasks_per_node: 1
cpus_per_task: 16
gpus_per_node: 1
mem_gb: null
# job_name: ${name}

# SlurmConf
partition: gpu_h100
max_num_timeout: 0

# Job configuration
account: null
qos: null
exclude: null

# Python environment setup
setup:
  - "source ~/.bashrc"
  - "module purge"
  - "cd ~/boa/"
  - "source .venv/bin/activate"
  - "export CUDA_VISIBLE_DEVICES=$SLURM_LOCALID"

additional_parameters:
  signal: "SIGUSR1@300"
  open-mode: "append"
  export: "NONE"

# submitit_folder: ${paths.log_dir}/.submitit/${name}
