# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

# BaseConf
# Time Settings
timeout_min: 4320
# signal_delay_s: 180 seems to send USR2
# Node Settings
nodes: 1
tasks_per_node: 1
cpus_per_task: 16
gpus_per_node: 1
mem_gb: 64
job_name: ${name}
stderr_to_stdout: true

# SlurmConf
partition: gpu-single
max_num_timeout: 0

# Job configuration
account: null
qos: null
exclude: null

# Python environment setup
setup:
  - "source ~/.bashrc"
  - "module purge"
  - "module load devel/cuda/12.6"
  - "module load compiler/gnu/14.1"
  - "mkdir -p $TMPDIR"
  - "tar --use-compress-program=unzstd -xf /gpfs/bwfor/work/ws/hd_ai306-dft_data/data/${data.dataset_name}.tar.zst -C \"$TMPDIR\""
  - "export BOA_DATA=$TMPDIR"
  - "export BOA_MODELS=/gpfs/bwfor/work/ws/hd_ai306-dft_data/models"
  - "cd ~/boa/"
  - "source .venv/bin/activate"
  - "export CUDA_VISIBLE_DEVICES=$SLURM_LOCALID"
  - "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"
  - "export HYDRA_FULL_ERROR=1"

additional_parameters:
  signal: "SIGUSR1@180"
  open-mode: "append"
  export: "ALL"

submitit_folder: "${hydra.sweep.dir}/%j_submitit_logs"
