# @package _global_

defaults:
  - override /trainer: slurm
  - override /hydra: slurm


trainer:
  limit_train_batches: 10
  limit_val_batches: 2

hydra:
  launcher:
    partition: gpu_a100_short
    signal_delay_s: 150
    additional_parameters:
      signal: "SIGUSR1@150"
    # Submitit configuration
    timeout_min: 5
